### ISSUE TITLE
Incorrect value of headers in yaml file could still be matched 

### ISSUE THREAD

**Issue by capton586** [0x727/ObserverWard#125]
The content of yaml file:
```
name: H3C
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {'www-authenticate': 'ww-authenticate'}
    keyword:
    favicon_hash: []

```
verify the file:

```
./observer_ward --verify h3c.yaml -t http://58.214.253.118:8002/
 __     __     ______     ______     _____
/\ \  _ \ \   /\  __ \   /\  == \   /\  __-.
\ \ \/ ".\ \  \ \  __ \  \ \  __<   \ \ \/\ \
 \ \__/".~\_\  \ \_\ \_\  \ \_\ \_\  \ \____-
  \/_/   \/_/   \/_/\/_/   \/_/ /_/   \/____/
Community based web fingerprint analysis tool.
_____________________________________________
:  https://github.com/0x727/FingerprintHub  :
:  https://github.com/0x727/ObserverWard    :
 --------------------------------------------
URL: http://58.214.253.118:8002/
HEADERS:
server: H3C-Miniware-Webs
date: Fri Feb 24 11:19:12 2023
www-authenticate: Basic realm="H3C ER5200"
pragma: no-cache
cache-control: no-cache
content-type: text/html
STATUS_CODE: 401
TEXT:
<html><head><title>�ĵ�����: δ��ȩ��</title></head>
                <body><h2>���ʴ���: δ��ȩ��</h2>
                ��ͼ����ҳ�� <b>/</b><br><p>������ҫ�û���</p></body></html>


Matching fingerprintV3WebFingerPrint {
    name: "H3C",
    priority: 3,
    request: WebFingerPrintRequest {
        path: "/",
        request_method: "get",
        request_headers: {},
        request_data: "",
    },
    match_rules: WebFingerPrintMatch {
        status_code: 0,
        favicon_hash: [],
        headers: {
            "www-authenticate": "ww-authenticate",
        },
        keyword: [],
    },
}
[ http://58.214.253.118:8002/ |["H3C"] | 233 | 401 | �ĵ�����: δ��ȩ�� ]
Important technology:
+-----------------------------+------+--------+-------------+-----------------+----------+
| url                         | name | length | status_code | title           | priority |
+=============================+======+========+=============+=================+==========+
| http://58.214.253.118:8002/ | H3C  | 233    | 401         | �ĵ�����: δ��ȩ�� | 4        |
+-----------------------------+------+--------+-------------+-----------------+----------+
```
 The target header is : www-authenticate: Basic realm="H3C ER5200"
but still match the rule. 
So someting wrong whith the rule or I didn't get the right way.
